/**
 * The shape of a turntable model and its triangle mesh. Shapes are generated by
 * scripts/turntable/bake.py from photos of the product; see that script for how.
 */

/** One horizontal slice: [y, x0, x1, z0, z1] in body heights (y up, z toward the bag's front). */
export type TurntableRow = readonly [number, number, number, number, number];

export interface TurntableShape {
  /** Superellipse exponent of every slice: 2 is an ellipse, higher values are boxier. */
  exponent: number;
  /** Rotation of the poster and of the first frame, in degrees (0 = front). */
  startAngle: number;
  /** Box the model stays inside at every rotation (width, height) and the height of its centre, in body heights. */
  viewport: { width: number; height: number; centerY: number };
  /** Slices from bottom to top. */
  rows: readonly TurntableRow[];
}

export interface TurntableMesh {
  /** x, y, z per vertex. */
  positions: Float32Array<ArrayBuffer>;
  /** u, v per vertex: u goes once round the slice, v runs from the top (0) to the bottom (1). */
  uvs: Float32Array<ArrayBuffer>;
  indices: Uint16Array<ArrayBuffer>;
}

/** Point of the unit superellipse |x|^n + |z|^n = 1 at parameter t (radians). */
export function superellipsePoint(t: number, exponent: number): [number, number] {
  const c = Math.cos(t);
  const s = Math.sin(t);
  const power = 2 / exponent;
  return [Math.sign(c) * Math.abs(c) ** power, Math.sign(s) * Math.abs(s) ** power];
}

/**
 * Rings of `segments` quads between consecutive slices. The texture was baked with the same parameterisation
 * (column = parameter t, row = height), so the mesh needs no other texture mapping.
 */
export function buildTurntableMesh(shape: TurntableShape, segments = 96): TurntableMesh {
  const { rows, exponent } = shape;
  const ringSize = segments + 1; // the seam vertex is repeated with u = 1
  if (rows.length < 2 || rows.length * ringSize > 0xffff) throw new RangeError("Unsupported turntable shape size");

  const top = rows[rows.length - 1][0];
  const bottom = rows[0][0];
  const unit = Array.from({ length: ringSize }, (_, j) => superellipsePoint((2 * Math.PI * j) / segments, exponent));
  const positions = new Float32Array(rows.length * ringSize * 3);
  const uvs = new Float32Array(rows.length * ringSize * 2);

  rows.forEach(([y, x0, x1, z0, z1], i) => {
    const cx = (x0 + x1) / 2;
    const cz = (z0 + z1) / 2;
    const a = (x1 - x0) / 2;
    const b = (z1 - z0) / 2;
    const v = (top - y) / (top - bottom);
    unit.forEach(([ex, ez], j) => {
      const k = i * ringSize + j;
      positions.set([cx + a * ex, y, cz + b * ez], k * 3);
      uvs.set([j / segments, v], k * 2);
    });
  });

  const indices = new Uint16Array((rows.length - 1) * segments * 6);
  let n = 0;
  for (let i = 0; i < rows.length - 1; i++) {
    for (let j = 0; j < segments; j++) {
      const a = i * ringSize + j;
      const c = a + ringSize;
      indices.set([a, c, a + 1, a + 1, c, c + 1], n);
      n += 6;
    }
  }
  return { positions, uvs, indices };
}

/**
 * Clip-space scale (x, y) that fits the shape's viewport inside a canvas of `width` × `height` pixels, centred,
 * like CSS `object-fit: contain` does with the poster, so poster and canvas line up.
 */
export function viewportScale(shape: TurntableShape, width: number, height: number): [number, number] {
  const pixelsPerUnit = Math.min(width / shape.viewport.width, height / shape.viewport.height);
  return [(2 * pixelsPerUnit) / width, (2 * pixelsPerUnit) / height];
}
